setwd("C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1")
library(sf)
library(ggplot2)
library(dplyr)
library(raster)
library(units)
library(rnaturalearth)
require(rgdal)
require(raster)
require(sf)
require(rgeos)
require(gdistance)
require(ggplot2)
set_crs("coordinate" <- "+proj=utm +zone=10 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0")
options(max.print = 99999)
read.table("RestSiteReuse_Complete.txt", sep = "," , header = T)
boundary = readOGR(dsn = "C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1", layer = "boundary83")
disturbance = readOGR(dsn = "C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1", layer = "disturbance")
lidar_roads = readOGR(dsn = "C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1", layer = "lidar_roads_sm")
lidar_stream = readOGR(dsn = "C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1", layer = "lidar_stream")
nhdwaterbody = readOGR(dsn = "C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1", layer = "nhdwaterbody")
riverslarge = readOGR (dsn =  "C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1", layer = "rivers_large_oregonexplorer")
riversOR = readOGR (dsn ="C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1", layer = "rivers_ORspatialdatalib")
r = raster("latlong_bare_earth.tif")
list.files("C:/Users/alex/Documents/Skunk paper/GIS/Skunkr/othergislayers1")
r = raster("latlong_bare_earth.tif")
plot("r")
df = as.data.frame(r, xy = T)
r = aggregate(r, fact = 20)
plot(r)
df = as.data.frame(r, xy = T)
r2 = raster("ogsi_2012_smoothed.tif")
df2 = as.data.frame(r2, xy = T)
plot(r2)
read.table("RestSiteReuse_Complete.txt", header = TRUE , sep = ",")
nad83z10 <- "+proj=utm +zone=10 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0"

biosites.sp <- SpatialPointsDataFrame(coords= "RestSiteReuse_Complete.txt"[("UTM_E","UTM_N")], data = "RestSiteReuse_Complete.txt", proj4string = CRS(nad83z10))
names("RestSiteReuse_Complete.txt")
install.packages("sp")
library("sp")
biosites.sp <- SpatialPointsDataFrame (coords = "RestSiteReuse_Complete.txt" [,c("UTM_E","UTM_N")], data = "RestSiteReuse_Complete.txt" , proj4string = CRS(nad83z10))
restsites <- read.csv("RestSiteReuse_Complete.txt" , stringsAsFactors = FALSE)
str(restsites)
names(restsites)
head(restsites2$UTM_E)
head(restsites2$UTM_N)
restsites <- SpatialPointsDataFrame(restsites[,12:13], restsites, proj4string = nad83z10)
read.table("restsiteedited.txt", header = TRUE , sep = ",")
restsites2 <- read.csv("restsiteedited.txt" , stringsAsFactors = FALSE)
restsites2 <- SpatialPointsDataFrame(restsites2 [,12:13] , restsites2)
plot(restsites2)
require(ggplot2)
require(raster)
require(sp)
geom_sf(data = boundary, fill = "grey", color = "grey") +
geom_sf(data = disturbance, fill = "black", color = "grey") +
geom_sf(data = restsites2, aes=(color = Sub_Type), color = "black")
plot(r2)
plot(boundary)
plot(disturbance, lwd = .1, col = "grey", add = TRUE)
plot(lidar_roads, lwd = .4, add = TRUE)
plot(lidar_stream, lwd = .05 , col = "blue",  add = TRUE)
plot(restsites2, pch= 16, cex = 0.2, col= "red", add = TRUE)  
plot(riversOR, lwd = .1, col = "green", add = TRUE)
plot(r2, add = TRUE)
shortest.dists <- numeric(nrow(restsites2)) 
for (UTM_E + UTM_N in restsites2(nrow(restsites2)) {shortest.dists(UTM) <- gDistance(restsites2[UTM,], disturbance)}
head(disturbance)
dim(disturbance)
str(disturbance)
head(disturbance)
object.size(disturbance)
plot(together)
names(disturbance)
require(raster)
require(rgdal)
shp2raster <- function(disturbance, mask.raster, polygons, m, transform = FALSE, proj.from = NA,proj.to = NA, map = TRUE)
rasterize(disturbance, mask.raster, field=data, background=bkg.value, filename=label) 
r <- rasterize(disturbance, mask.raster)
r[!is.na(r)] <- value
r <- mask(merge(r, mask.raster), mask.raster, filename = disturbance, format = "GTiff",
          overwrite = T) 
disturbance <- rasterize(disturbance, mask.raster, field=polygons, filename=label)
names(BiodiversityArea)
str(BiodiversityArea)
library(sp)
library(raster)
library(rgeos)
library(spatstat)
library(rgdal)     
library(maptools)

bd <- union(disturbance, BiodiversityArea)
